name: Update Pendle Portfolio

on:
  schedule:
    - cron: '0 10 * * 1'  # Run every Monday at 10:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit changes back to the repository
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run portfolio tracker
        env:
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        run: python portfolio_tracker.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add portfolio_history.csv latest_data.json portfolio_summary.json
          git commit -m "Update portfolio data: $(date -u)" || echo "No changes to commit"
          git push
